name: flutter_async_button
description: A useful wrapper for Flutter buttons to support async operations
version: 1.0.3

homepage: https://www.quantos.it

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
