name: flutter_async_button
description: A useful wrapper for Flutter buttons to support async operations
version: 0.0.1
homepage: https://Www.quantos.it

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
